name : demo-actions-matrix
on : [push, pull_request]

jobs:

  matrix_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        java: [ '8', '11', '13', '15' ]
    name: Java ${{ matrix.java }} running on ${{matrix.os}}
    steps:
     - uses: actions/checkout@v2
     - name: Setup java
       uses: actions/setup-java@v2
       with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
     - run: java -version
     - run: echo " ====== Say Hello from Java ${{matrix.java}} =========="
